### ISSUE TITLE
API #1 -- avatars

### ISSUE THREAD

**Issue by golemheavy** [bratwurst-productions/LCR-Game#21]
use an API to render the player's APIs. All players will see the same avatar image for a given player.

**Comment by golemheavy** [comment]
https://github.com/bratwurst-productions/LCR-Game/issues/3

check the comments of issue 3 for some APIs including avatar APIs like dicebear.

**Comment by MuhammetH** [comment]
https://www.tutorialsteacher.com/nodejs/nodejs-module-exports 
This website could be helpful to understand what is module.exports in js files that inside of the generator and data folders...

**Comment by lonesomecowboy42** [comment]
randomized avatars from avataaars.io were implemented.

if we decide to implement reaction emotion animations, that will be handled in a different issue.
