### ISSUE TITLE
Music API

### ISSUE THREAD

**Issue by golemheavy** [bratwurst-productions/LCR-Game#22]
two possible apis to use for this feature:

spotify

last.fm

**Comment by golemheavy** [comment]
we could implement it as follows: let the user/player choose and switch between channels / genres.

Rock / dubstep / jazz /etc

**Comment by golemheavy** [comment]
last FM uses a radio with tag... this may be the simplest way to implement API music..

**Comment by lonesomecowboy42** [comment]
this issue is being re-classified as a nice to have, and will be closed. We don't want to cause a code overhead burden for a feature with limited desirability and limited utility.
