### ISSUE TITLE
Establish initial variables for each player and handle logic to handle things like boolean playersturn? Win condition etc.

### ISSUE THREAD

**Issue by eg22453** [bratwurst-productions/LCR-Game#24]

**Comment by golemheavy** [comment]
Check for win condition at beginning of player turn

**Comment by golemheavy** [comment]
need a boolean for each player: MyTurn: true / false

**Comment by golemheavy** [comment]
All players' browsers will maintain a full synchronized copy of all data stored in the firebase realtime database.

**Comment by lonesomecowboy42** [comment]
win conditions were done (by you). they may need to be rewritten to allow for games spectating / multiple games, but that will be handled in a different issue.
