### ISSUE TITLE
Research Using API's creatively

### ISSUE THREAD

**Issue by eg22453** [bratwurst-productions/LCR-Game#3]
Put in the comments below API's we can use for the elements for our page. Sound/Music/Graphics etc..

**Comment by golemheavy** [comment]
Creative Commons for background images.

**Comment by golemheavy** [comment]
for avatars, here are 21 APIs:

https://www.programmableweb.com/category/avatars/api

https://getavataaars.com

**Comment by golemheavy** [comment]
the link above yielded this for avatars: https://www.programmableweb.com/api/dicebear-avatar-male and the other version:
https://www.programmableweb.com/api/dicebear-avatar-male

**Comment by golemheavy** [comment]
for music we probably only need like one, but if there are different options of channels that may be nice. tho MVP doesn't need music.

a good search on music API produced a lot of interesting things:

https://www.google.com/search?q=music+api&oq=music+api&aqs=chrome..69i57j0l5.6873j0j7&sourceid=chrome&ie=UTF-8

including napster, music machinery, musikki and more.
also soundcloud, spotify, last.fm, Rdio, etc

**Comment by golemheavy** [comment]
a google search on sound effect APIs also produced a wealth of goodness:

https://www.google.com/search?q=sound+effect+apis&oq=sound+effect+apis&aqs=chrome..69i57j0.3646j0j7&sourceid=chrome&ie=UTF-8

**Comment by golemheavy** [comment]
Sound library from google developers
freesound API
web audio API
audio jungle royalty free music and sound

**Comment by MuhammetH** [comment]
https://github.com/spotify/web-api-auth-examples

spotify api examples might be helpful.

**Comment by MuhammetH** [comment]
API key = f836e22bf2def1723bfe5f949336e8a6

https://www.last.fm/api

no idea how to use this API but I created an account anyway.

**Comment by golemheavy** [comment]
We're currently planning to use the following two APIs to fulfill our API requirement:

getavataaars.com

https://getavataaars.com/?accessoriesType=Prescription02&avatarStyle=Circle&clotheColor=PastelOrange&clotheType=ShirtVNeck&eyeType=Close&eyebrowType=RaisedExcitedNatural&facialHairColor=BrownDark&facialHairType=MoustacheMagnum&graphicType=Pizza&hairColor=SilverGray&hatColor=White&mouthType=ScreamOpen&skinColor=Light&topType=LongHairShavedSides

and for music last.fm
