### ISSUE TITLE
more css reorg

### ISSUE THREAD

**Issue by golemheavy** [bratwurst-productions/LCR-Game#31]
Check it out. I am changing the layout to be more pleasing to the eye.

- I removed padding from the jumbotron

- I made the game pane longer to match the right column

- I added some air space between the columns

- I moved the name and chat inputs into the "card header" div and removed the "card body" div.

I think that covers it, but take a look and approve please

**Comment by lonesomecowboy42** [comment]
I just adjusted the style and layout to fix issues with the mobile and non mobile views.
