### ISSUE TITLE
define all game behavior

### ISSUE THREAD

**Issue by golemheavy** [bratwurst-productions/LCR-Game#8]
we need to have game behavior nailed down very definitely.

**Comment by golemheavy** [comment]
I propose the following behavior:

The page will tell all visitors: X players connected.
Whenever a player clicks to start a new game, the game starts a countdown to begin a game.
All players are notified that a game will be starting after countdown, and how many players are waiting to play.
If the game doesn't get at least three players to join before it starts, it cancels. 
If at least 3 visitors join before game starts, the game begins.

**Comment by golemheavy** [comment]
the initial button will be shown as Start if no game is yet started, or Join if a game has been started.

**Comment by deceptikhan81** [comment]
If a player has fewer than three chips left, he is still in the game but his number of chips is the number of dice he rolls on his turn, rather than rolling all three. When a player has zero chips, he passes the dice on his turn, but may receive chips from others and take his next turn accordingly. The winner is the last player with chips left. He does not roll the dice, and wins the center pot.

**Comment by deceptikhan81** [comment]
First we need a function to act as the dice, secondly we need a function that takes the resulting dice rolls and moves the chips around accordingly, and lastly we need a function that will play the game till completion. We will also write a function to plot the course of the game, and a function to summarize the game.

**Comment by golemheavy** [comment]
Ok, so I want to propose a refinement to the behavioral definition proposed above:

no longer will there be a timer.

Now, the order is this:
when you connect, you are in the connected pool
You have the option to Join and be placed in the waiting pool
As soon as there are at least three players in the waiting pool, those players and those players only will see a button appear or become active which is a "Start Game" button. 
As soon as one of the waiting players clicks the Start Game button, the game will begin will all the players who are in the waiting pool.
Anyone who connects while the game is ongoing or who didn't join the waiting pool before the game started has to wait until the game is over.
The game should also allow for people to quit, though we don't need a button for that. They can leave by closing their browser tab or by having their connection drop.
As a nice to have, if a player doesn't roll within a given amount of time, the game will roll for them, perhaps with a warning or a visible countdown.

**Comment by golemheavy** [comment]
working the above-defined start logic in branch issue8

**Comment by golemheavy** [comment]
note: if someone accidentally drops or closes browser tab / connection, they forfeit chips to center pot.

**Comment by golemheavy** [comment]
note about disabling buttons:

adding an attribute "disabled" to a button tag will cause the button to become unclickable and also changes the opacity to be less opaque.

`<button disabled></button>`

So I propose the following to indicate a button is disabled:

1. add the attribute
2. prepend `<em>` or `<i>` tags around the button text to change it to italics
3. change button class from btn-primary to btn-secondary to change button color from blue to gray.

These three things together will both indicate the button is inactive to the use as well as make it unresponsive to that button's click listener, without having to interrupt or disable the click listener.

**Comment by lonesomecowboy42** [comment]
most of the above has been implemented. forfeiting chips has not, but that issue and others will be handled in separate issues.
